### ISSUE TITLE
Wheel name should include Python tag 

### ISSUE THREAD

**Issue by mwmattis** [karpierz/pyc_wheel#12]
Hi,

please have a look at this [spec](https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#platform-compatibility-tags).

> The wheel built package format includes these tags in its filenames, of the form {distribution}-{version}(-{build tag})?-{python tag}-{abitag}-{platform tag}.whl

I store pyc-wheels for PyPy as well as CPyton on a custom index. In order to give pip the chance to resolve the correct wheel for a specific Python version and implementation, the wheel name needs to contain the [Python tag](https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#python-tag).

What do you think?

BR,

Mattis

**Comment by karpierz** [comment]
Ready: https://pypi.org/project/pyc-wheel/ (1.3.0)
