### ISSUE TITLE
python -m pyc_wheel any.whl is not working

### ISSUE THREAD

**Issue by Alone-on-the-edge** [karpierz/pyc_wheel#3]
I am not sure what the issue is, but if try to run the above command, it doesnt give me any error not it gives me "any.whl"

**Comment by karpierz** [comment]
Please give full info about used command and full info about env (Python version, OS name and version, pyc_whell version) you used.

**Comment by karpierz** [comment]
Close, because cannot be reproduced without detailed info.

**Comment by mayank-iisc** [comment]
Hi,
I am experiencing the following issue in Windows 10, Python 3.6 version.
> python -m pyc_wheel mywheel-0.0.1-py3-none-any.whl
C:\Users\my-pc\AppData\Local\Programs\Python\Python36\python.exe: No module named pyc_wheel

I tried using older versions of pyc_wheel but it didn't help. I have created wheels using pyc_wheel 1.24.0 for Python 3.7, 3.8, 3.9 in Windows 10 and they are working fine.

Please help.

Thanks and Regards,
Mayank

**Comment by mayank-iisc** [comment]
I resolved the above issue by following these steps:
1- Downloaded the pyc_wheel-1.2.4.zip from PyPI repo of pyc_wheel.
2- Unzipped the zip file and copied **pyc_whee**l folder within C:\....\Downloads\pyc_wheel-1.2.4\src\ to Python 3.6 site packages folder.
3- Usual location of this folder is within: C:\Users\user1\AppData\Local\Programs\Python\Python36\Lib\site-packages\

Still there is some problem happening during pip install pyc_wheel within Python3.6 which needs a fix. These steps should get automatically executed.

**Comment by karpierz** [comment]
@mayank-iisc Sorry, I cannot reproduce your problem.
On my box (Windows10), also for Py3.6 (3.6.8) pyc_wheel works fine:
```
C:\Python36>python.exe -m pip install -U pyc_wheel
Looking in indexes: http://adcam.aptiv.com:3141/root/stable, https://pypi.org/simple
Collecting pyc_wheel
  Downloading https://files.pythonhosted.org/packages/00/14afb6313825ec33f23cd09f3a3726ee71687ac67feef2d3770b020850c964/pyc_wheel-1.2.4.zip
Collecting setuptools>=42.0.2 (from pyc_wheel)
  Downloading https://files.pythonhosted.org/packages/a2/e1/902fbc2f61ad6243cd3d57ffa195a9eb123021ec912ec5d811acf54a39f8/setuptools-57.1.0-py3-none-any.whl (818kB)
    100% |████████████████████████████████| 819kB 3.6MB/s
Installing collected packages: setuptools, pyc-wheel
  Found existing installation: setuptools 40.6.2
    Uninstalling setuptools-40.6.2:
      Successfully uninstalled setuptools-40.6.2
  Running setup.py install for pyc-wheel ... done
Successfully installed pyc-wheel-1.2.4 setuptools-57.1.0
You are using pip version 18.1, however version 21.1.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Python36>python.exe -m pyc_wheel
usage: __main__.py [-h] [--exclude EXCLUDE] [--with_backup] [--quiet] whl_file
__main__.py: error: the following arguments are required: whl_file

C:\Python36>python.exe -m pyc_wheel lxml-4.6.3-cp36-cp36m-win_amd64.whl
Listing 'C:\\Users\\gjtrd0\\AppData\\Local\\Temp\\tmpgl_usan0'...
Listing 'C:\\Users\\gjtrd0\\AppData\\Local\\Temp\\tmpgl_usan0\\lxml'...
Compiling 'C:\\Users\\gjtrd0\\AppData\\Local\\Temp\\tmpgl_usan0\\lxml\\ElementInclude.py'...
Compiling 'C:\\Users\\gjtrd0\\AppData\\Local\\Temp\\tmpgl_usan0\\lxml\\__init__.py'...
Compiling 'C:\\Users\\gjtrd0\\AppData\\Local\\Temp\\tmpgl_usan0\\lxml\\_elementpath.py'...
[...]
Deleting py file: C:\Users\gjtrd0\AppData\Local\Temp\tmpgl_usan0\lxml\html\__init__.py
Deleting py file: C:\Users\gjtrd0\AppData\Local\Temp\tmpgl_usan0\lxml\includes\__init__.py
Deleting py file: C:\Users\gjtrd0\AppData\Local\Temp\tmpgl_usan0\lxml\isoschematron\__init__.py
```
and produced proper wheel file

Adam

**Comment by karpierz** [comment]
@mayank-iisc : Always use this way to install python package:
```
    python -m pip install -U pyc_wheel
```
Don't use:
```
    pip install -U pyc_wheel
```
I suppose that improper pip is in your PATH (probbably from different python).
Check it by:
where pip

Adam

**Comment by mayank-iisc** [comment]
Hi Adam,

I tried installing through the method which you have mentioned for Python 3.6.1, but still facing the same issue.

![image](https://user-images.githubusercontent.com/23032384/125263401-9c8ee080-e320-11eb-9ad5-8cb310f054e6.png)

![image](https://user-images.githubusercontent.com/23032384/125263494-b2040a80-e320-11eb-950d-80b09839bcfa.png)

**Comment by karpierz** [comment]
Please upgrade pip and related:  python -m pip install --upgrade --upgrade-strategy eager pip setuptools wheel
and try again:
python -m pip uninstall pyc-wheel
python -m pip install --upgrade pyc-wheel
Let me know what happened (I really cannot reproduce this issue).

Adam
