### ISSUE TITLE
script files are stripped from executable bit

### ISSUE THREAD

**Issue by harmv** [karpierz/pyc_wheel#5]
pyc_wheel fails to keep the executable bit on python scripts.

A python package can contain a script file, which has the executable bit set and a proper shebang line in the front.

usecase: python packages that want to provide an 'executable'
for example pip itself is such script

`which pip`
That is a python script. 
* Its python
* it has the executable bit set
* It does not have a .py extension

A python package can contain a number of these scripts (optionally).
These are specified in setup.py in `scripts`

example
```
setup(
...
   scripts=['scripts/kar_diag', 'scripts/kard']
...)
```

When you build a wheel, and install the wheel, these files land in some /bin/  directory, with the executable bit set.

### steps to reproduce
1. Take a wheel with some scripts say  foo.whl.
If you pip install the wheel the script kard  lands in thee ../bin dir with the executable bit set. So far so good.
2. convert the wheel using pyc_wheel
python -m pyc_wheel  foo.whl

3. install the wheel
  pip install foo.whl

### result
The script lost its executable bit in the pyc_wheel step
```
user@system:~$ ls -la v/bin/kard
-rw-rw-r-- 1 user user 284 Feb 24 15:59 v/bin/kard
```

### expected result
The script has the executable bit set. Thats what happens if you skip the pyc_wheel step.

**Comment by nsw42** [comment]
Ignore PR8 - I renamed my branch to correct a poor choice of name. PR9 is based on the new branch name,
