### ISSUE TITLE
compiled wheel file from windows and import error gets thrown in linux

### ISSUE THREAD

**Issue by aswinselva03** [karpierz/pyc_wheel#6]
Hi,

I have compiled the wheel file using pyc and installed the same in linux. But when importing the module i'm getting the below error. Any idea how to solve this?

ImportError while loading conftest '/usr/app/tests/test_scripts/conftest.py'.
conftest.py:12: in <module>
    from PyAuto.PyAutoException import handle_selenium_exception, PyAutoExceptions
E   ImportError: bad magic number in 'PyAuto': b'a\r\r\n'

**Comment by karpierz** [comment]
Hi
*.whl fies (and also *.pyc file) are platform and even Python version specific so using it on different Python and/or platform in not possible.
Adam
